### PR TITLE
Added serialisation support using cereal

### PR DESCRIPTION
**Pull request by bsipos**
Hello!

For one of my projects, I needed a way to efficiently serialize to disk the graphs constructed by spoa.
These modifications achieve that using the [cereal](https://uscilab.github.io/cereal/) library which I have found very practical to use.
To comply with the requirements of cereal, I had to add some default constructors and make some existing ones public. I have also added a couple of utility methods.
I am not very well versed in cmake, so the way I pull in cereal might not be the best.
Would you consider merging these additions into master (maybe after a bit of polishing). The amount of code I have added is pretty minimal.

Best,
Botond

### CODE REVIEW

**Comment by rvaser** [comment]
Hi Botond,
I see no problem in integrating `cereal` into the master branch. Do you mind if I reorganize your code a bit? I saw there are a lot of differences due to different indent sizes and open/closed parantheses.

Best regards,
Robert

**Comment by bsipos** [comment]
Sure no problem. I am using clang-format which messed up your original indentation style a bit :)
Thanks,
Botond

**Comment by rvaser** [comment]
Hi Botond,
I finally implemented your PR into spoa. Please check out refactor branch and let me know if anything else is needed. I'll merge it into master soon.

Sorry for the wait!
Best regards,
Robert

**Comment by rvaser** [comment]
Available at master branch.

**Pull request closed without merging**
