### PR TITLE
write GFA paths in reverse when alignment is reversed

### PR DESCRIPTION
**Pull request by ekg**
This adds another feature to the spoa executable, so that when a GFA output is selected and the alignment is reversed, we get the path embedded in the correct orientation.

### CODE REVIEW

**Comment by ekg** [comment]
Hi @rvaser, I'm curious if this is up to your standards. It's essential for my use of spoa's command line executable, FWIW.

**Comment by rvaser** [comment]
Hi @ekg, it looks alright but I was in the middle of a refactor and wanted to incorporate your feature request in a different way. Then I went on a vacation for the last two weeks. I'll try to finish everything by the end of this week. Really sorry that I prolonged everything this much.

**Comment by ekg** [comment]
Not a worry at all! I just picked it back up and was curious what you thought.

**Comment by rvaser** [comment]
Hi Erik,
I have finally implemented everything you requested, please checkout the refactor branch and let me know if anything else is needed. I'll merge it into master soon.

I am really sorry for the delay!
Best regards,
Robert

**Comment by rvaser** [comment]
Available at master branch.

**Comment by ekg** [comment]
Thank you @rvaser I'm just getting back to this now to sync up with your updates.

**Pull request closed without merging**
