### PR TITLE
Add cereal include

### PR DESCRIPTION
**Pull request by cjw85**
I tried making the project with:

    mkdir build && cd build && cmake -D spoa_optimize_for_portability=ON -DCMAKE_BUILD_TYPE=Release -D CMAKE_CXX_FLAGS="-fPIC" .. && make

but hit:

    spoa/graph.hpp:14:29: fatal error: cereal/access.hpp: No such file or directory

### CODE REVIEW

**Comment by rvaser** [comment]
Which cmake version do you have? Compilation works for me without the `include_directories` command.

**Comment by cjw85** [comment]
Hmm, `cmake version 3.18.2`

**Comment by rvaser** [comment]
Tried the same command on the same cmake version and compilation finishes.

**Comment by cjw85** [comment]
Yeah, its working for me now too. :/

Not sure what was happening the first time around.

**Pull request closed without merging**
